# Generated by Django 5.2.5 on 2025-08-27 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='musicfile',
            name='performer',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='musicfile',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
