# Generated by Django 5.2.5 on 2025-08-29 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_musicfile_performer_musicfile_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='musicfile',
            name='duration',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='musicfile',
            name='file_size',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
