# Generated by Django 5.2.5 on 2025-08-31 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0004_musicsearch_musicplay'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='musicfile',
            name='caption',
        ),
    ]
